- name: 克隆 ARL-docker 项目
  ansible.builtin.git:
    repo: https://github.com/honmashironeko/ARL-docker
    dest: /opt/ARL-docker
    update: false  # 只在目录不存在时克隆，已存在时不更新
  register: git_clone
  when:
    - arl_enable | bool

- name: 设置 setup_docker.sh 脚本执行权限
  ansible.builtin.file:
    path: /opt/ARL-docker/setup_docker.sh
    mode: '0755'
  when:
    - arl_enable | bool

- name: 执行 ARL 安装脚本
  ansible.builtin.shell: bash setup_docker.sh
  args:
    chdir: /opt/ARL-docker
    executable: /bin/bash
  register: arl_install
  changed_when: true
  when:
    - arl_enable | bool
    - not ansible_check_mode
